# Generated by Django 2.2.2 on 2019-06-05 10:22

from django.db import migrations, models
import django.db.models.deletion
import djangoShop.models
import djangoShop.storage


class Migration(migrations.Migration):

    dependencies = [
        ('djangoShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=djangoShop.storage.OverwriteStorage(), unique=True, upload_to=djangoShop.models.generate_path),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoShop.Product')),
            ],
        ),
    ]
