# Generated by Django 2.2.2 on 2019-06-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoShop', '0003_auto_20190606_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.TextField(),
        ),
    ]
