# Generated by Django 2.2.2 on 2019-06-06 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoShop', '0004_auto_20190606_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
